stages:
    - build
    - test
    
variables:
   registry: gitlab.thevirtualbrain.org:5000
   CONTAINER_TEST_IMAGE: gitlab.thevirtualbrain.org:5000/anywave/anywave:$CI_BUILD_REF_NAME
   CONTAINER_UBUNTU_IMAGE: gitlab.thevirtualbrain.org:5000/anywave/anywave:ubuntu
   CONTAINER_RELEASE_IMAGE:  gitlab.thevirtualbrain.org:5000/anywave/anywave:latest
   USER: anywave

before_script:
   - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $registry
   
build:
   stage: build
   script:
     - docker build -t $CONTAINER_UBUNTU_IMAGE -f Docker/Dockerfile-aw-ubuntu Docker
     - docker push  $CONTAINER_UBUNTU_IMAGE
     - docker build -t $CONTAINER_TEST_IMAGE -f Docker/Dockerfile-aw .
     - docker push $CONTAINER_TEST_IMAGE

test:
   stage: test
   script:
     - docker run --rm $CONTAINER_TEST_IMAGE --version
only:
    - master