stages:
    - build
run-build:
    stage: build
    script:
        - apt-get install -y  qt5-default libqt5-dev libvtk6-dev libopenblas-base libopenblas-dev
        - mkdir build
        - cd build
        - cmake ..
        - make
        
#AnyWave:
#   image: debian:stretch
#    script:
#        - apt-get install qt5-default libqt5-dev libvtk6-dev libopenblas-base libopenblas-dev
#        - apt-get install tcsh libfftw3-dev qtbase5-dev libqwt-qt5-dev qttools5-dev-tools libqt5script5
#        - apt-get instal libqt5scripttools5 qtscript5-dev libqt5svg5-dev libXt-dev libhdf5-dev
#        - mkdir build
#        - cd build
#        - cmake ..
#        - make