variables:
   registry: gitlab.thevirtualbrain.org:5000
   ubuntu: anywave/anywave/aw-ubuntu
   tag: anywave/anywave
   
build:
   stage: build
   script:
     - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $registry
     - docker build -t $registry/$ubuntu -f Docker/Dockerfile-aw-ubuntu Docker
     - docker push $registry/$ubuntu
     - docker build -t $registry/$tag -f Docker/Dockerfile-aw .
     - docker push $registry/$tag
      
test:
   stage: test
   image: $registry/$tag
   script:
     - docker run --rm -v /data:/data anywave/anywave --version