FROM gitlab.thevirtualbrain.org:5000/anywave/anywave:ubuntu

RUN apt-get install -y sudo
USER root
ADD sudoers.txt /etc/sudoers
RUN chmod 440 /etc/sudoers

RUN useradd -ms /bin/bash anywave && echo "anywave:anywave" | chpasswd && adduser anywave sudo
USER anywave
CMD /bin/bash
WORKDIR /home/anywave

COPY ./armadillo /home/anywave/armadillo
COPY ./include /home/anywave/include
COPY ./resources /home/anywave/resources
COPY ./src /home/anywave/src
COPY ./cmake /home/anywave/cmake
COPY CMakeLists.txt /home/anywave
 
RUN mkdir /home/anywave/build
WORKDIR /home/anywave/build
RUN cd /home/anywave/build && cmake -DCMAKE_INSTALL_PREFIX=/usr/local .. && sudo make install

ADD entrypoint.sh /bin/entrypoint.sh
RUN chmod +x /bin/entrypoint.sh
CMD /bin/entrypoint.sh