FROM gitlab.thevirtualbrain.org:5000/anywave/anywave:ubuntu

USER root
RUN apt-get install -y xvfb x11vnc fluxbox

#ADD sudoers.txt /etc/sudoers
#RUN chmod 440 /etc/sudoers

#RUN useradd -ms /bin/bash anywave && echo "anywave:anywave" | chpasswd && adduser anywave sudo
#USER anywave
#CMD /bin/bash
#WORKDIR /home/anywave

COPY ./armadillo /home/anywave/armadillo
COPY ./include /home/anywave/include
COPY ./resources /home/anywave/resources
COPY ./src /home/anywave/src
COPY ./cmake /home/anywave/cmake
COPY CMakeLists.txt /home/anywave
 
RUN mkdir /home/anywave/build
WORKDIR /home/anywave/build
RUN cd /home/anywave/build && cmake -DCMAKE_INSTALL_PREFIX=/usr/local .. && make install

