# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

HEADERS += ../../include/montage/AwMontage.h  ../../include/montage/AwAVGChannel.h

SOURCES += ./AwMontage.cpp ./AwAVGChannel.cpp
