# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

HEADERS += ../../include/AwMontage.h 

SOURCES += ./AwMontage.cpp
