#ifndef APPENDFILES_GLOBAL_H
#define APPENDFILES_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef APPENDFILES_LIB
# define APPENDFILES_EXPORT Q_DECL_EXPORT
#else
# define APPENDFILES_EXPORT Q_DECL_IMPORT
#endif

#endif // APPENDFILES_GLOBAL_H
